### ISSUE TITLE
How to set `reverseLayout` when LazyList has `reverseLayout = true`?

### ISSUE THREAD

**Issue by thedroiddiv** [GIGAMOLE/ComposeScrollbars#1]

**Comment by GIGAMOLE** [comment]
Hi, thanks for the issue. Can you explain why you need it? Preferably, some screenshots, like actual/desired. I didn't add this feature initially because I thought it was useless.

**Comment by thedroiddiv** [comment]
Let's say in a chat app, the list is shown usually bottom-up. So when the scroll is 0 then pill should be at bottom and when scroll is non-zero pill should be at any appropriate location.
 
## Expected:

https://github.com/GIGAMOLE/ComposeScrollbars/assets/69595691/a051703e-8d7e-42a9-9c63-a1e0625e0db5

## Actual

https://github.com/GIGAMOLE/ComposeScrollbars/assets/69595691/5c1727c4-82a4-449e-9dbb-7dd3e1304cb1

**Comment by thedroiddiv** [comment]
Currently, I'm using this hack to achieve the required behaviour. `RotationX = 180F`

```kotlin
Scrollbars(
    state = scrollbarsState,
    modifier = Modifier.graphicsLayer { rotationX = 180F }
)               
```

**Comment by GIGAMOLE** [comment]
Hi. This feature has been added in a new release: https://github.com/GIGAMOLE/ComposeScrollbars/releases/tag/1.0.4
Thanks for the improvement.
