### ISSUE TITLE
How to use with `LazyList`?

### ISSUE THREAD

**Issue by christophehenry** [GIGAMOLE/ComposeScrollbars#2]
The documentation just states "*Just place it on top of your scrollable content.*". But if I use it like this:

```kotlin
@Composable
private fun FeedList() {
    val listState = rememberLazyListState()
    
    Row {
        Scrollbars(…)
        LazyColumn(state = listState, modifier = Modifier.weight(1f).fillMaxSize()) { … }
    }
}
```

The `LazyColumn` is not displayed: it has a width of 0. If I remove the `Row`, then the scrollbar isn't displayed.

**Comment by GIGAMOLE** [comment]
Hi.

Just place it above (Z-order) of your scrollable content so its visible. (Changed in Readme).
And from what I see, you haven't checked the sample app :)

As you can see, you are using Row, which is not correct,  The Scrollbars takes all place (fillMaxSize by default) so the LazyColumn is pushed out and has 0 size.

Do something like this, example:

```kotlin
Box(modifier = Modifier.fillMaxSize()) {
    LazyColumn(
        modifier = Modifier.fillMaxSize(),
        state = lazyListState
    ) {
        // Populate items here.
    }
    Scrollbars(state = scrollbarsState)
  }
```

**Comment by christophehenry** [comment]
I couldn't find any `LazyColumn` in the sample app but maybe I just missed it. Anyway, thanks for the help!
