### ISSUE TITLE
Publish for compose multiplatform 

### ISSUE THREAD

**Issue by StefanLobbenmeier** [GIGAMOLE/ComposeScrollbars#3]
It looks like at the moment this library is only published as an android library, not for compose multiplatform, right? I took a brief look at the imports and did not see any native android imports, so it would be nice to make this library available on other platforms as well.

One benefit I would like to highlight even for android only users is that this would enable publishing the sample as a compose web app, so you can try it right in your browser

**Comment by StefanLobbenmeier** [comment]
Did not get that far today, but shared my progress so far in #4

**Comment by GIGAMOLE** [comment]
Hi. I got your point and I checked the PR, and I did not like how the project started to look. If you want to do a KMP support, create a fork, because I will decline the PR.

**Comment by KunMinX** [comment]
@StefanLobbenmeier Can your share be used on KMP? I've looked at your share, in ScrollbarsState.kt there is still an import statement for `android.view.MotionEvent`. Is this usable for desktop? Are there any solutions?

**Comment by StefanLobbenmeier** [comment]
Never tried it, but I am assuming there would be some more code changes needed

**Comment by KunMinX** [comment]
@StefanLobbenmeier Haha, implementing a scrollbar is actually quite convenient now; the official library provides it, so there's no need for this additional library.

**Comment by StefanLobbenmeier** [comment]
Yeah I saw the official support for scrollbars, but by default they’re quite minimalistic, I was hoping to use this library to have more native looking scrollbars.
