### ISSUE TITLE
Add MRE(Minimal reproducible example) to test library easy and fast

### ISSUE THREAD

**Issue by KovshefulCoder** [GIGAMOLE/ComposeScrollbars#7]
The sample app provides a lot of setup and configuration, which is great! 

However, if I just want to quickly test your library and see how it works, there’s no simple, concise example to follow. Instead, I have to dig into the sample app's source code, which includes many settings that I don’t need at the moment, making it overwhelming to try the library for the first time

**Comment by GIGAMOLE** [comment]
Hi, thanks for the feedback. You spent time creating this issue, rather than reading the library documentation. First, I won't do the simple sample (the first time you run the sample app, it's simple by default). Second, explore it.
